project:
  title: "DIY Corsi-Rosenthal Box"
  type: website
  output-dir: _site

website:
  navbar:
    left: 
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu: 
          - text: Source code
            url: https://github.com/anielsen001/diy-corsi-rosenthal-box
  sidebar:
    search: true
    style: floating
    contents: 
      - section: "Variants"
        contents:
          - text: Box Fan
            file: boxfan.qmd
          - text: Honeywell HT-908
            file: honeywell-ht908.qmd
          - pc_case_fan.qmd


format:
  html: 
    toc: true

bibliography:
  - cr.bib
